stages:
  download:
    cmd: python train.py download
    deps:
      - arxiv_paper_classifier/utils/dvc_utils.py
      - arxiv_paper_classifier/commands.py
    outs:
      - data/raw/arxiv-metadata-oai-snapshot.json:
          cache: true
          remote: data-store
          push: true

  preprocess:
    cmd: python train.py preprocess
    deps:
      - data/raw/arxiv-metadata-oai-snapshot.json
      - arxiv_paper_classifier/data/preprocessing.py
      - arxiv_paper_classifier/utils/label_utils.py
      - configs/preprocessing/default.yaml
      - configs/data/arxiv.yaml
    outs:
      - data/processed/preprocessor.pkl:
          cache: true
          remote: data-store
          push: true

  train:
    cmd: python train.py train
    deps:
      - data/processed/preprocessor.pkl
      - arxiv_paper_classifier/
      - configs/
    outs:
      - models/best_model.ckpt:
          cache: true
          remote: model-store
          push: true
    metrics:
      - plots/metrics.json:
          cache: false

  infer:
    cmd: python train.py infer
    deps:
      - models/best_model.ckpt
      - data/processed/preprocessor.pkl
      - arxiv_paper_classifier/commands.py
      - configs/
    outs:
      - plots/inference_results.csv:
          cache: false
